### ISSUE TITLE
Error inflating ImageButton cwac camera

### ISSUE THREAD

**Issue by mnafian** [ParkSangGwon/TedPicker#2]
I have this issue when use your library, i have test this on android JB 4.1.2 .

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      android.view.InflateException: Binary XML file line #50: Error inflating class ImageButton
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                          at com.gun0912.tedpicker.CwacCameraFragment.onCreateView(CwacCameraFragment.java:104)
                                                                          at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                          at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                          at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                          at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                          at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                                          at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                                          at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                                          at android.view.View.measure(View.java:15193)
                                                                          at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
                                                                          at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
                                                                          at android.view.View.measure(View.java:15193)
                                                                          at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:617)
                                                                          at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:399)
                                                                          at android.view.View.measure(View.java:15193)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                          at android.view.View.measure(View.java:15193)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
                                                                          at android.view.View.measure(View.java:15193)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at android.view.View.measure(View.java:15193)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                          at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1390)
                                                                          at android.widget.LinearLayout.measureVertical(LinearLayout.java:681)
                                                                          at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
                                                                          at android.view.View.measure(View.java:15193)
                                                                          at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4816)
                                                                          at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                          at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2152)
                                                                          at android.view.View.measure(View.java:15193)
                                                                          at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1850)
                                                                          at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1102)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1275)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4216)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                                          at android.os.Handler.handleCallback(Handler.java:615)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:4794)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      	at java.lang.reflect`

**Comment by ParkSangGwon** [comment]
thanks.
that error appear under lollipop.
fixed at v1.0.3
